<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Person;
use Illuminate\Support\Facades\Hash;

class PersonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $people = [
            // Personas Físicas - Régimen Simplificado de Confianza (626) - G03 Gastos en general
            [
                'legalName' => 'XOCHILT CASAS CHAVEZ',
                'email' => 'xochilt.casas@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'CACX7605101P8',
                'zipCode' => '36257',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'KARLA FUENTE NOLASCO',
                'email' => 'karla.fuente@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'FUNK671228PH6',
                'zipCode' => '01160',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'LUIS IAN ÑUZCO',
                'email' => 'luis.ian@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'IAÑL750210963',
                'zipCode' => '85256',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'ADRIANA JUAREZ FERNANDEZ',
                'email' => 'adriana.juarez@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'JUFA7608212V6',
                'zipCode' => '01160',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'OSCAR KALA HAAK',
                'email' => 'oscar.kala@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'KAHO641101B39',
                'zipCode' => '76074',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'RODRIGO KITIA CASTRO',
                'email' => 'rodrigo.kitia@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'KICR630120NX3',
                'zipCode' => '36246',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'CECILIA MIRANDA SANCHEZ',
                'email' => 'cecilia.miranda@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'MISC491214B86',
                'zipCode' => '01010',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'ÑEVES RAMIREZ QUEZADA',
                'email' => 'neves.ramirez@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'RAQÑ7701212M3',
                'zipCode' => '78905',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'MARIA WATEMBER TORRES',
                'email' => 'maria.watember@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'WATM640917J45',
                'zipCode' => '43543',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'XAIME WEIR ROJO',
                'email' => 'xaime.weir@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'WERX631016S30',
                'zipCode' => '01279',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'ALBA XKARAJAM MENDEZ',
                'email' => 'alba.xkarajam@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'XAMA620210DQ5',
                'zipCode' => '01219',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'BERENICE XIMO QUEZADA',
                'email' => 'berenice.ximo@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'XIQB891116QE4',
                'zipCode' => '40968',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'INGRID XODAR JIMENEZ',
                'email' => 'ingrid.xodar@ejemplo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'XOJI740919U48',
                'zipCode' => '76028',
                'satTaxRegimeId' => '626',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],

            // Personas Morales - General de Ley Personas Morales (601) - G03 Gastos en general
            [
                'legalName' => 'ESCUELA KEMPER URGATE',
                'email' => 'contacto@escuelakemper.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'EKU9003173C9',
                'zipCode' => '42501',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'INDISTRIA ILUMINADORA DE ALMACENES',
                'email' => 'contacto@iia.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'IIA040805DZ4',
                'zipCode' => '62661',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'HERRERIA & ELECTRICOS',
                'email' => 'contacto@herreriayelectricos.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'H&E951128469',
                'zipCode' => '06002',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'INNOVACION VALOR Y DESARROLLO',
                'email' => 'contacto@ivd.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'IVD920810GU2',
                'zipCode' => '63901',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'INTERNACIONAL XIMBO Y SABORES',
                'email' => 'contacto@ximbo.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'IXS7607092R5',
                'zipCode' => '23004',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'JIMENEZ ESTRADA SALAS',
                'email' => 'contacto@jes.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'JES900109Q90',
                'zipCode' => '37161',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'KERNEL INDUSTIA JUGUETERA',
                'email' => 'contacto@kij.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'KIJ0906199R1',
                'zipCode' => '28971',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
            ],
            [
                'legalName' => 'LUCES & OBRAS',
                'email' => 'contacto@lucesyobras.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'L&O950913MSA',
                'zipCode' => '60922',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'ORGANICOS ÑAVEZ OSORIO',
                'email' => 'contacto@organicosno.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'OÑO120726RX3',
                'zipCode' => '40501',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'S & SOFTWARE',
                'email' => 'contacto@syssoftware.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'S&S051221SE2',
                'zipCode' => '76022',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'UNIVERSIDAD ROBOTICA ESPAÑOLA',
                'email' => 'contacto@ure.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'URE180429TM6',
                'zipCode' => '86991',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'XENON INDUSTRIAL ARTICLES',
                'email' => 'contacto@xenon.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'XIA190128J61',
                'zipCode' => '76343',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
            [
                'legalName' => 'ZAPATERIA URTADO ÑERI',
                'email' => 'contacto@zapateriaun.com',
                'password' => Hash::make('Admin12345!'),
                'tin' => 'ZUÑ920208KL4',
                'zipCode' => '34541',
                'satTaxRegimeId' => '601',
                'satCfdiUseId' => 'G03',
                'taxPassword' => '12345678a',
            ],
        ];

        foreach ($people as $person) {
            Person::create($person);
        }
    }
}
